version: '3.8'

services:
  server:
    build: ./server
    container_name: server
    volumes:
      - ./www:/var/www/html
    ports:
      - 8080:80
    env_file:
      - .env
    depends_on:
      - database
  
  database:
    image: surrealdb/surrealdb:latest
    container_name: database
    entrypoint:
      - /surreal
      - start
      - --user
      - $DB_USER
      - --pass
      - $DB_PASSWORD
    ports:
      - 8000:8000
