version: '3.8'

services:
  server:
    build: .
    container_name: server
    volumes:
      - ./public:/var/www/html
      - ./src:/var/www/html/src
    ports:
      - 8080:80
    env_file:
      - .env
    depends_on:
      - database
  
  database:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: pri
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  pgdata: