version: '3.8'

services:
  server:
    build: .
    container_name: server
    volumes:
      - ./public:/var/www/html
      - ./src:/var/www/html/src
    ports:
      - 8080:80
    env_file:
      - .env
    depends_on:
      - mongodb
      - mongo-express
  
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
    volumes:
      - mongo_data:/data/db
  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: woid
      ME_CONFIG_MONGODB_ADMINPASSWORD: helloworld
      ME_CONFIG_MONGODB_URL: mongodb://woid:helloworld@mongodb:27017/
      ME_CONFIG_BASICAUTH: false

volumes:
  mongo_data:
