version: '3.8'

services:
  server:
    build: ./server
    container_name: server
    volumes:
      - ./www:/var/www/html
    ports:
      - 8080:80
    env_file:
      - .env
    depends_on:
      - database
  
  database:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: pri
    ports:
      - 5432:5432