version: '3.8'

services:
  frontend:
    build:
      context: ./public
    container_name: frontend
    volumes:
      - ./public:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - appnet

  backend:
    build:
      context: ./src
    container_name: backend
    volumes:
      - ./src:/var/www/html/
    ports:
      - "80:80"
    env_file:
      - .env
    depends_on:
      - mongodb
      - mongo-express
    networks:
      - appnet
  
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
    volumes:
      - mongo_data:/data/db
  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: woid
      ME_CONFIG_MONGODB_ADMINPASSWORD: helloworld
      ME_CONFIG_MONGODB_URL: mongodb://woid:helloworld@mongodb:27017/
      ME_CONFIG_BASICAUTH: false

networks:
  appnet:
    driver: bridge

volumes:
  mongo_data:
